manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      # https://github.com/zmkfirmware/zmk/commit/6217664bc32b673dc61fcc1825b3ceebe418b44b
      revision: 6217664bc32b673dc61fcc1825b3ceebe418b44b
      import: app/west.yml
  self:
    path: config
