on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@f72f415c5bd23a89d7e50b1a8e22ede70c0db9e3

